INSPJT/instagram_clone_backend

src/main/java/our/yurivongella/instagramclone/InstagramcloneApplication.java

tab to space

---

src/main/resources/application.yml

CI 실행 중 DB close 현상 트러블 슈팅
db url에 다음 코드를 추가했습니다.
````
;DB_CLOSE_ON_EXIT=FALSE

feat : Add DB_CLOSE_DELAY

---

src/test/resources/application.yml

Test yaml에 설정이 누락되어 추가합니다.
- CI test시 db close를 처리하지 않습니다.

feat : edit datasource url for CI

---

.github/workflows/gradle.yml

Test Coverage 60% 미만 빌드 실패
- circleci.yml 수정

feat : Add Coverage Rule in CI

---

src/main/java/our/yurivongella/instagramclone/controller/dto/MemberRequestDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDto.java

#15 관련 수정
`Users` 가 적절하지 않아 `Member` 로 변경하고 관련 코드들 전부 변경
- Users -> Member

refactor: DTO 네이밍 변경: Users -> Member

---

Dockerfile
build.gradle
src/main/java/our/yurivongella/instagramclone/config/WebConfig.java
src/main/resources/application.yml

Dockerfile과 CORS 설정.
추가로, default profile로 mysql이 동작하도록 추가했습니다.
- Dockerfile, WebConfig

Add Dockerfile and CORS

---

Docker-compose.yml
Dockerfile
build.gradle
src/main/java/our/yurivongella/instagramclone/config/WebConfig.java
src/main/resources/application.yml

default profile을 h2 환경으로 변경
origin 모두 허용(임시)
- web config, application.yml, docker-compose(임시)

feat: fix Default profile, allow all origin

---

Dockerfile
build.gradle

```
docker build -t "이미지 이름" .
```
를 하면 project build -> docker build까지 한번에 됩니다.
- dockerfile

build : fix dockerfile

---

src/main/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/SigninRequestDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/SignupRequestDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/TokenRequestDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
src/main/java/our/yurivongella/instagramclone/domain/member/Authority.java
src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
src/main/java/our/yurivongella/instagramclone/service/CommentService.java
src/test/java/our/yurivongella/instagramclone/controller/dto/MemberDtoTest.java
src/test/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDtoTest.java
src/test/java/our/yurivongella/instagramclone/service/AuthServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/CustomUserDetailsServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java

#32 에서 의논한 대로 수정
1. 프로필 이미지는 profileImageUrl 컬럼으로 추가
2. nickname 은 @Nullable, displayId 는 @NotNull 로 Unique
3. Email 컬럼도 Unique 설정
- name -> dispalyId 로 변경하고 Unique 설정
- nickName -> nickname 변경
- email 컬럼 Unique 설정
- profileImageUrl 컬럼 추가

chore: Member Entity 컬럼 변경 및 추가

---

src/main/resources/application.yml

h2-console을 확인할 수 있도록 cors 설정을 열어두었습니다.
```
spring.h2.console.settings.web-allow-others를 true로 설정
```

feat : Add Web Cors h2-console

---

src/main/java/our/yurivongella/instagramclone/domain/member/MemberRepository.java
src/main/java/our/yurivongella/instagramclone/exception/CustomException.java
src/main/java/our/yurivongella/instagramclone/exception/ErrorCode.java
src/main/java/our/yurivongella/instagramclone/exception/ErrorResponse.java
src/main/java/our/yurivongella/instagramclone/exception/GlobalExceptionHandler.java
src/main/java/our/yurivongella/instagramclone/jwt/TokenProvider.java
src/main/java/our/yurivongella/instagramclone/service/AuthService.java
src/main/java/our/yurivongella/instagramclone/service/MemberService.java
src/main/java/our/yurivongella/instagramclone/util/SecurityUtil.java
src/main/resources/application.yml

Spring 에서 Exception 을 좀 더 편리하고 명확하게 처리하기 위한 코드입니다.
개인적으로 정리한 내용은 [Wiki - Spring Exception Handling](https://github.com/INSPJT/instagram_clone_backend/wiki/Spring-Exception-Handling) 을 참고하시면 됩니다. (글이 너무 길다 싶으면 3 번 챕터만 봐도 됩니다)
에러 정책이나 포맷 같은걸 저 혼자 정했기 때문에 다른 의견이 있을수 있어서 우선 모든 API 에 적용하지 않고 Member, Auth API 에만 적용했습니다.
`ErrorCode`, `ErrorResponse` 에 대해서 자유롭게 의견 주세요.
- Exception Handler 추가
- Member, Auth API  에서 RuntimeException 사용하던 것들 리팩토링

feat: Exception Handling 추가

---

.github/workflows/gradle.yml

master 브랜치에서도 V 체크 보이게 하려고 추가
- gradle.yml 에 master 브랜치 추가

build: add master branch

---

src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
src/main/java/our/yurivongella/instagramclone/controller/PostController.java
src/main/java/our/yurivongella/instagramclone/controller/ProfileController.java
src/main/java/our/yurivongella/instagramclone/controller/dto/MediaUrlDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileMemberDto.java
src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfilePostDto.java
src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
src/main/java/our/yurivongella/instagramclone/domain/follow/Follow.java
src/main/java/our/yurivongella/instagramclone/domain/follow/FollowRepository.java
src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
src/main/java/our/yurivongella/instagramclone/domain/post/MediaUrl.java
src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
src/main/java/our/yurivongella/instagramclone/domain/post/PostLikeRepository.java
src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
src/main/java/our/yurivongella/instagramclone/service/CommentService.java
src/main/java/our/yurivongella/instagramclone/service/MemberService.java
src/main/java/our/yurivongella/instagramclone/service/PostService.java
src/main/java/our/yurivongella/instagramclone/service/ProfileService.java
src/main/java/our/yurivongella/instagramclone/util/DateTimeUtil.java
src/main/resources/data.sql
src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/ProfileServiceTest.java

자세한 내용은 커밋 참고
- Profile API 추가
- `/feeds` API 에서 `lastPostId` 파라미터 required -> optional 로 변경

2021. 04. 03. 배포

---

.github/workflows/cicd.yml
Dockerfile
src/main/resources/application.yml

- logging level을 INFO level로 변경
- 컨테이너 내부 volume 지정

Add logging as file

---

.github/workflows/cicd.yml
Dockerfile

app.jar -> insta.jar
8080 -> 80

hotfix dockerfile

---

.github/workflows/cicd.yml

nginx 라우팅이 8080으로 되어 있어서 원래 상태로 수정
- 컨테이너 실행시 호스팅을 8080 -> 8080으로 설정

edit docker hosting port

---

Dockerfile
build.gradle
src/main/java/our/yurivongella/instagramclone/InstagramcloneApplication.java
src/main/java/our/yurivongella/instagramclone/config/QuerydslConfig.java
src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
src/main/java/our/yurivongella/instagramclone/domain/SliceHelper.java
src/main/java/our/yurivongella/instagramclone/domain/post/CustomPostRepository.java
src/main/java/our/yurivongella/instagramclone/domain/post/MediaUrl.java
src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
src/main/java/our/yurivongella/instagramclone/domain/post/PostRepositoryImpl.java
src/main/java/our/yurivongella/instagramclone/service/CommentService.java
src/main/java/our/yurivongella/instagramclone/service/PostService.java
src/main/java/our/yurivongella/instagramclone/service/S3Service.java
src/main/resources/application-local.yml
src/main/resources/application-real.yml
src/test/java/our/yurivongella/instagramclone/InstagramcloneApplicationTests.java
src/test/java/our/yurivongella/instagramclone/domain/comment/CommentRepositoryTest.java
src/test/java/our/yurivongella/instagramclone/service/AuthServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/CustomUserDetailsServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/FollowServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
src/test/java/our/yurivongella/instagramclone/service/ProfileServiceTest.java
src/test/resources/application.yml

* Querydsl 적용
* temp rds
* fix test
* delete sysout

vault 및 rds, querydsl (#97)

---

src/main/resources/application-real.yml

RDS URL 수정
- application-real.yml

edit rds url

---

src/main/resources/application-real.yml

Reverts INSPJT/instagram_clone_backend#99

Revert "edit rds url"

---

src/main/resources/application-real.yml

Vault URL 수정

---

build.gradle

fix : Project version Rollback
